module builtin_interfaces
{

module msg
{

module dds_
{




struct Time_
{

  long sec_;
  unsigned long nanosec_;

};  // struct Time_


};  // module dds_

};  // module msg

};  // module builtin_interfaces
